### ISSUE TITLE
can not evaluate with CAPTURE metric with multiprocessing samples 

### ISSUE THREAD

**Issue by xdeng7** [foundation-multimodal-models/CAPTURE#2]
Does anyone run into the following problem?

![image](https://github.com/user-attachments/assets/8e474a5c-fc3b-47e1-9e3e-aca456363f75)

**Comment by Dousia** [comment]
This error is caused by wrongly formatted input predictions and ground truths.  Please refer to this repo's homepage for expected input formats. CAPTURE requires just the same input format as other metrics in pycocoevalcap.
